name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ] # somehow windows-latest is failing; dont have time for that, *nixes work
        python-version: [
          "3.11",
          "3.12"
        ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        run: |
          python -m pip install -r ./requirements.txt
          python -m unittest
          # this fixture was prepared to show how to use run_all/run_current_module; each file must be executed as separate process
          python -m test_fixture.x
          python -m test_fixture.y
          python -m test_fixture.run_all
